#81
Senzing/g2configtool pull request #83
Opened 2022-08-17 04:32 UTC by jbutcher21

2022-08-17 16:01 UTC, antaenc commented on G2ConfigTool.py
> +except:
This should catch the expected exception:

except (ImportError, ModuleNotFoundError):

2022-08-17 16:02 UTC, antaenc commented on G2ConfigTool.py
> +                Senzing compares records within and across data sources.  Records consist of features and features have attributes.
Double space

2022-08-17 16:02 UTC, antaenc commented on G2ConfigTool.py
> +                For instance, the NAME feature has attributes such as NAME_FIRST and NAME_LAST, even NAME_ORG for an organization.
Change even to and

2022-08-17 16:03 UTC, antaenc commented on G2ConfigTool.py
> +                Features are standardized, expressed in various ways to create candidate keys, and compared to see how close they
standardized and expressed

2022-08-17 16:04 UTC, antaenc commented on G2ConfigTool.py
> +                Finally, a set of rules or "principles" are applied to each candidate record's scores to see if the incoming record should resolve
candidate should be plural

2022-08-17 16:04 UTC, antaenc commented on G2ConfigTool.py
> +                    help basic      <- for commonly used commands
Remove the < use only -

2022-08-17 16:05 UTC, antaenc commented on G2ConfigTool.py
> +                To understand more about configuring Senzing, please review ...
No ..., use : instead

2022-08-17 16:11 UTC, antaenc commented on G2ConfigTool.py
> +        self.intro = '\nType help or ? to list commands.\n'
Change this back to ='', this message is displayed in the preloop function which is called upon startup and when restarting due to a config change. Now it duplicates the same message:

```
--> ./G2ConfigTool_butcher.py 

Initializing Senzing engines...

Welcome to G2Config Tool. Type help or ? to list commands.


Type help or ? to list commands.
```

2022-08-17 16:13 UTC, antaenc commented on G2ConfigTool.py
> +                    listFeatures table
table is optional consider calling this out or surrounding it in [ ] to highlight it's optional

2022-08-17 16:15 UTC, antaenc commented on G2ConfigTool.py
> +            New features and their attributes are rarely needed.  But when they are they are usually industry specific
Double spacing

2022-08-17 16:15 UTC, antaenc commented on G2ConfigTool.py
> +            identifiers (F1s) like medicare_provider_id or swift_code for a bank.  If you want some other kind of attribute like a grouping (FF)
Double spacing

2022-08-17 16:15 UTC, antaenc commented on G2ConfigTool.py
> +                    listFeatures        <- to list all the features in the system
Change to -

2022-08-17 16:15 UTC, antaenc commented on G2ConfigTool.py
> +                Here are the commands to add or update attributes ...
: not ...

2022-08-17 16:16 UTC, antaenc commented on G2ConfigTool.py
> +                Here are the commands for using templates
Add a : to end to be consistent

2022-08-17 16:16 UTC, antaenc commented on G2ConfigTool.py
> +                    templateAdd         <- add an identifier (F1) feature and attributes based on a template
- not <

2022-08-17 16:17 UTC, antaenc commented on G2ConfigTool.py
> +                    listFeatures            <- to see what features are used for candidates
- not <

2022-08-17 16:17 UTC, antaenc commented on G2ConfigTool.py
> +                    addToNamehash           <- to add to the name and ... keys
Why the ...?

2022-08-17 16:18 UTC, antaenc commented on G2ConfigTool.py
> +                            command above or add new expressions by using the addExpressionCall command above.
You don't need to say above here for both these commands.

2022-08-17 16:18 UTC, antaenc commented on G2ConfigTool.py
> +            Once the candidate matches have been found, scoring and rule evaluation takes place next.  Scores are rolled up by behavior.
Remove the next, it's implied.

2022-08-17 16:18 UTC, antaenc commented on G2ConfigTool.py
> +            For instance, both addresses and phones have the behavior FF (Frequency Few). So if they both score above their scoring
Remove So

2022-08-17 16:19 UTC, antaenc commented on G2ConfigTool.py
> +            function's close threshold, there would be two CLOSE_FFs (a fragment) which can be used in a rule such as NAME+CLOSE_FF.
function not function's

2022-08-17 16:19 UTC, antaenc commented on G2ConfigTool.py
> +                    listRules               <- these are the rules that
No < just -

2022-08-17 16:20 UTC, antaenc commented on G2ConfigTool.py
> +                - history = Display all history
If changing this to history, change histClear and histDedupe to historyClear and historyDedupe too. Also change in G2Command to be consistent.

2022-08-17 16:24 UTC, antaenc commented on G2ConfigTool.py
> +            self.cfgData = json.load(open(arg), encoding="utf-8")
This is incorrect and should be: self.cfgData = json.load(open(arg, encoding="utf-8"))
There was a backwards breaking change in the API in Python3.9 that results in: 

```
(g2cfg) exportToFile /tmp/config

Successfully exported!

(g2cfg) importFromFile /tmp/config
ERROR: __init__() got an unexpected keyword argument 'encoding'
  File "/home/ant/senzprojs/3.1.2.22182/python/G2ConfigTool_butcher.py", line 306, in cmdloop
    cmd.Cmd.cmdloop(self)

  File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)

  File "/usr/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)

  File "/home/ant/senzprojs/3.1.2.22182/python/G2ConfigTool_butcher.py", line 832, in do_importFromFile
    self.cfgData = json.load(open(arg), encoding="utf-8")

  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),

  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
```

2022-08-17 16:24 UTC, antaenc commented on G2ConfigTool.py
> +            listDataSources <optionalFilter> <optionalParameter>
Optional should be surrounded with [ ]

2022-08-17 16:24 UTC, antaenc commented on G2ConfigTool.py
> +            listDataSources             <-to list all dataSources in json format
- not <

2022-08-17 16:25 UTC, antaenc commented on G2ConfigTool.py
> +            listDataSources table       <-to list all dataSources in a table format
These don't need to be prefixed with to, remove

2022-08-17 16:29 UTC, antaenc commented on G2ConfigTool.py
> +            listFunctions <optionalFilter> <optionalParameter>
Optionals in [ ]

2022-08-17 16:29 UTC, antaenc commented on G2ConfigTool.py
> +            listFunctions             <-to list all functions in json format
no < just -

2022-08-17 16:30 UTC, antaenc commented on G2ConfigTool.py
> +            listFeatures             <-to list all features in json format
You know this one :)

2022-08-17 16:33 UTC, antaenc commented on G2ConfigTool.py
> +            If you need to add one manually, it is best to clone an existing one by doing a getFeature on one like it,
If you need to add a feature manually, it is recommended to clone an existing and similar one with getFeature

2022-08-17 16:34 UTC, antaenc commented on G2ConfigTool.py
> +            and editing its json configuration in your favorite editor.  You will need to at least change its "id" and
and editing the JSON. You will need to at least change "id" and

2022-08-17 16:35 UTC, antaenc commented on G2ConfigTool.py
> +            "feature" code so they are unique, but you can change anything else you like.  Then when you are ready, use
"feature" codes to be unique, you can change anything else required. When ready, use

2022-08-17 16:35 UTC, antaenc commented on G2ConfigTool.py
> +            it as the addRecord <json configuration>.
the modified JSON with addRecord <json configuration>.

2022-08-17 16:36 UTC, antaenc commented on G2ConfigTool.py
> +            And don't forget to add the attributes for its elements using the addAttribute command!
Remove And

2022-08-17 16:36 UTC, antaenc commented on G2ConfigTool.py
> +            This command appends an attribute from another feature to the name hash.  In the example above, the street number
Double space

2022-08-17 16:36 UTC, antaenc commented on G2ConfigTool.py
> +            getAttribute NAME_LAST             <- shows attribute json
You know this one by now

2022-08-17 16:40 UTC, antaenc requested changes
Syntax and small changes mostly to improve readability.

2022-08-18 20:41 UTC, jbutcher21 commented on G2ConfigTool.py
> +except:
Only important if I were gonna report that specifically.   If no pretty table, then no pretty table support.   warning to install it is later if they even try to use it.

2022-08-18 20:48 UTC, jbutcher21 commented on G2ConfigTool.py
> +                    help basic      <- for commonly used commands
why?   I much prefer the arrow

2022-08-18 21:02 UTC, jbutcher21 commented on G2ConfigTool.py
> +                            command above or add new expressions by using the addExpressionCall command above.
not sure what you mean.  I like this.

2022-08-18 21:05 UTC, jbutcher21 commented on G2ConfigTool.py
> +            function's close threshold, there would be two CLOSE_FFs (a fragment) which can be used in a rule such as NAME+CLOSE_FF.
Nope, it is possive

2022-08-18 21:05 UTC, jbutcher21 commented on G2ConfigTool.py
> +                    listRules               <- these are the rules that
disagree

2022-08-18 21:09 UTC, jbutcher21 commented on G2ConfigTool.py
> +                - history = Display all history
not important.   everyone uses history.   They other two are rarely used and can be looked up if needed.

2022-08-18 21:09 UTC, jbutcher21 commented on G2ConfigTool.py
> +            listDataSources             <-to list all dataSources in json format
disagree

2022-08-18 21:09 UTC, jbutcher21 commented on G2ConfigTool.py
> +            listDataSources table       <-to list all dataSources in a table format
disagree

2022-08-18 21:10 UTC, jbutcher21 commented on G2ConfigTool.py
> +            listFunctions             <-to list all functions in json format
disagree

2022-08-18 21:13 UTC, jbutcher21 commented on G2ConfigTool.py
> +            listFeatures <optionalFilter> <optionalParameter>
only obvious to a programmer.  I prefer as is.

2022-08-18 21:23 UTC, jbutcher21 commented on G2ConfigTool.py
> +            listFunctions <optionalFilter> <optionalParameter>
this for end users not programmers.  above is very clear.

2022-08-18 22:37 UTC, antaenc approved these changes

2022-08-18 22:37 UTC, merged